### ISSUE TITLE
https or not?

### ISSUE THREAD

**Issue by IonicaBizau** [bhuga/bhuga.net#1]
On your profile, the site url has the `https` protocol, but an error appears. Replacing `https` with `http` solves the problem.

![image](https://cloud.githubusercontent.com/assets/2864371/8112108/74f21a78-106e-11e5-904d-aae1a8d8c6c6.png)

**Comment by bhuga** [comment]
All things must come to an end, link fixed. thanks!

**Comment by IonicaBizau** [comment]
True! :+1:
